#!/usr/bin/env python3
from lib.google import get_service
from lib.upload import cleanup

import sys

def main(args):
    name = args[0]
    if (input('Are you sure you want to delete all drive files containing {}?'.format(name)).lower() 
            in ['yes', 'y']):
        drive = get_service('drive')
        cleanup(drive, name)

if __name__ == '__main__':
    sys.exit(main(sys.argv[1:]))


