#!/usr/bin/env python3
from collections import defaultdict
from pprint      import pprint
import pickle, sys

from lib.schedule import get_schedule

#******************************************************************************
#  Auxillary
#******************************************************************************

def get_tasks(filename):
    try:
        with open(filename, 'rb') as infile:
            tasks = pickle.load(infile)
    except FileNotFoundError as e:
        tasks = defaultdict(list)
    return tasks

def save_tasks(tasks, filename):
    with open(filename, 'wb') as outfile:
        pickle.dump(tasks, outfile)


 #******************************************************************************
 #  Subcommands
 #******************************************************************************

def add(tasks, schedule, taskData, duration):
    duration = int(duration)
    tasks[duration].append(taskData)
    return tasks

def do(tasks, schedule, duration, overwrite=True):
    duration = int(duration)
    possible = tasks[duration]
    if len(possible) == 0:
        print('No available tasks to be done')
    else:
        print('Next task:')
        print(possible[0])
        if overwrite:
            tasks[duration] = possible[1:]
    return tasks

def see(tasks, schedule, duration):
    duration = int(duration)
    print('Next task would be:')
    return do(tasks, duration, overwrite=False)

def next(tasks, schedule):
    pass

def view(tasks, schedule):
    pprint(tasks)

#******************************************************************************
#  Subcommand tree
#******************************************************************************

commands = {
        'view' : view,
        'add'  : add,
        'see'  : see,
        'do'   : do
        }

def main(args):
    schedule = get_schedule()

    if len(args) == 0:
        print('Please provide arguments to helper script')
        return 0

    filename = 'tasks.pkl'
    tasks = get_tasks(filename)

    subCommand, *text = args
    tasks = commands[subCommand](tasks, schedule, *text)

    save_tasks(tasks, filename)
    return 0

if __name__ == '__main__':
    sys.exit(main(sys.argv[1:]))
